Fix/mocked in cypress
Synthetixio/synpress pull request #1142
Opened 2024-06-10 07:31 UTC by matstyler

## Motivation and context

Clearly and concisely describe the feature added/isses being solved.

## Does it fix any issue?

#(issue)

## Other useful info

N/A

## Quality checklist

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough e2e tests.

**⚠️👆 Delete any section you see irrelevant before submitting the pull request 👆⚠️**

2024-06-14 21:01 UTC, drptbl requested changes
Great work sir, just need some answers to above - and changes if needed.

2024-06-14 21:01 UTC, drptbl commented on wallets/ethereum-wallet-mock/src/cypress/support/mockEthereum.ts
> +        wallet: 'metamask'
should we add ability to specify mocked wallet here?

2024-06-14 21:01 UTC, drptbl commented on wallets/ethereum-wallet-mock/src/cypress/support/e2e.ts
> +  return false
not sure if this is not going to fail a test when any critical error is thrown in browser console on any browser (not only related to wallet itself). do we want this behavior?

2024-06-14 21:01 UTC, drptbl commented on wallets/ethereum-wallet-mock/src/cypress/utils/installSynpress.ts
> +  // setupTasks(on);
do we want it here? we already import commands on `e2e.ts`

2024-06-15 21:15 UTC, matstyler commented on wallets/ethereum-wallet-mock/src/cypress/support/e2e.ts
> +  return false
It the opposite - it should prevent failing if possible.

2024-06-15 21:41 UTC, matstyler commented on wallets/ethereum-wallet-mock/src/cypress/support/mockEthereum.ts
> +        wallet: 'metamask'
It's a wallet for initial mock. User is able to connect a different wallet using `connectToDapp`.

2024-06-15 22:23 UTC, drptbl approved these changes

2024-06-15 22:23 UTC, merged