✨ feat: Add renameAccount method
Synthetixio/synpress pull request #1145
Opened 2024-06-11 11:39 UTC by Seroxdesign

## Motivation and context

- Allows us to name a metamask account

## Does it fix any issue?

#(issue)

## Other useful info

N/A

## Quality checklist

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough e2e tests.

**⚠️👆 Delete any section you see irrelevant before submitting the pull request 👆⚠️**

2024-06-14 21:02 UTC, drptbl requested changes, later dismissed

2024-06-14 21:02 UTC, drptbl commented on wallets/metamask/src/pages/HomePage/selectors/index.ts
> +  renameInput: 'input'
I would try to find a selector that is unique and applicable only to this particular element. `input` is too broad.

2024-06-18 08:07 UTC, localtechboy commented on wallets/metamask/src/pages/HomePage/selectors/index.ts
> +  renameInput: '.mm-text-field .mm-box--padding-right-4'
are you sure all of these selectors are new? looks like some of them may be the same as one of the existing ones

2024-06-18 08:07 UTC, localtechboy commented on wallets/metamask/src/pages/HomePage/actions/renameAccount.ts
> +  Account.parse({ name: newAccountName }) // Validate newAccountName against Account schema
I am not sure if we should validate it manually instead of leaving it for MetaMask to validate

2024-06-18 10:24 UTC, Seroxdesign commented on wallets/metamask/src/pages/HomePage/actions/renameAccount.ts
> +  Account.parse({ name: newAccountName }) // Validate newAccountName against Account schema
This was in the original scope of work requested by @drptbl in the old PR

2024-06-18 10:25 UTC, Seroxdesign commented on wallets/metamask/src/pages/HomePage/selectors/index.ts
> +  renameInput: '.mm-text-field .mm-box--padding-right-4'
will check ty

2024-06-18 14:04 UTC, Seroxdesign commented on wallets/metamask/src/pages/HomePage/selectors/index.ts
> +  renameInput: '.mm-text-field .mm-box--padding-right-4'
removed the single repeated selector, thanks for calling this out

2024-06-19 21:51 UTC, drptbl commented on wallets/metamask/src/pages/HomePage/actions/renameAccount.ts
> +  Account.parse({ name: newAccountName }) // Validate newAccountName against Account schema
@Seroxdesign if there is a problem of validation not being language agnostic, its probably better to leave validation for metamask like @matstyler said

2024-06-20 13:25 UTC, Seroxdesign commented on wallets/metamask/src/pages/HomePage/actions/renameAccount.ts
> +  Account.parse({ name: newAccountName }) // Validate newAccountName against Account schema
I removed that test as it doesn't cover all languages

2024-06-20 22:08 UTC, matstyler approved these changes

2024-06-24 15:18 UTC, merged