Update metamask
Synthetixio/synpress pull request #639
Opened 2023-02-12 11:02 UTC by r3kt-eth

hi,

1) updated metamask to new version
2) updated all flows to work with new version
3) fixed waitToBeHidden and added it to waitUntilStable
4) handled critical metamask error
5) updated documentation
6) updated trunk

this pull request fix critical issue with notifications in background too.

thx, cheerz.

2023-02-12 11:24 UTC, drptbl commented
Hey,

Thanks for contribution. I will review it asap.

Cheers,
Jakub.

2023-02-12 14:06 UTC, drptbl requested changes
Added few comments. Also, `importWallet` and `createWallet` looks very similar now and could be extracted to separate function instead of repeating it. Thanks 👍.

2023-02-12 14:06 UTC, drptbl commented on commands/metamask.js
> +      '999999999999999999',
can you please make this as an (optional) parameter?

2023-02-12 14:06 UTC, drptbl commented on pages/metamask/first-time-flow-page.js
> +
please remove this if it's not needed anymore

2023-02-12 20:26 UTC, drptbl approved these changes
LGTM

2023-02-12 20:27 UTC, merged

2023-02-24 19:17 UTC, ComradeAERGO commented
Didn't this breaks the tests?
It seems like the cy.get(#network) calls from the metamask-spec.js file all fail now.